###
GET  http://aksipriteps.site/api/user

###
PATCH  http://aksipriteps.site/api/user/6
Content-Type: application/json

{
    "name": "user Update",
    "email": "user@use.use",
    "password": "12345678",
    "role": "ADMIN"
}

###
POST http://aksipriteps.site/api/register
Content-Type: application/json

{
    "name": "user",
    "email": "user@use.use",
    "password": "1sampai8",
    "role": "USER"
}

###
POST http://aksipriteps.site/api/login
Content-Type: application/json

{
    "email": "use@use.use",
    "password": "1sampai8"
}

###
POST http://aksipriteps.site/api/post
Content-Type: application/json

{
    "title": "Hello Hello Bandung",
    "authorId": 1
}
###
POST  http://aksipriteps.site/api/kerusakan
Content-Type: application/json

{
    "kerusakanCode": "K03",
    "kerusakanName": "Kerusakan 3",
    "perbaikan": "Perbaikanna ini"
}

###
GET  http://aksipriteps.site/api/kerusakan

# EVIDENCE
###
GET http://aksipriteps.site/api/evidence

###
POST  http://aksipriteps.site/api/evidence
Content-Type: application/json

{
    "evidenceCode": "E06",
    "evidenceName": "Evidence 06"
}

###
DELETE  http://aksipriteps.site/api/evidence/1

# PENGETAHUAN

###
GET http://aksipriteps.site/api/pengetahuan
###
DELETE  http://aksipriteps.site/api/pengetahuan/3

###
POST http://aksipriteps.site/api/pengetahuan
Content-Type: application/json

{
    "kerusakanId": 2,
    "evidenceId": 2,
    "bobot": 0.8
}

# DIAGNOSA

###
GET   http://aksipriteps.site/api/diagnosa
###
POST http://aksipriteps.site/api/diagnosa
Content-Type: application/json

{
    "kerusakanId": 6,
    "userId": 1,
    "nilai": 87
}